# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
#    -   id: check-yaml
    -   id: check-added-large-files
    -   id: mixed-line-ending
        exclude: (template|ci).*\.(json|yml|yaml)$
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace
#- repo: https://github.com/astral-sh/ruff-pre-commit
#  # Ruff version.
#  rev: v0.6.7
#  hooks:
#    # Run the linter.
#    - id: ruff
#      args: [  ]
#    # Run the formatter.
#    - id: ruff-format
#- repo: https://github.com/pre-commit/mirrors-mypy
#  rev: v1.11.2  # Usa la última versión disponible
#  hooks:
#    - id: mypy  # Comprueba los tipos en código Python
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
    - id: isort
