
services:
  integration_sm_api_staging:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - TZ=America/Caracas
    container_name: integration_sm_api_staging
    ports:
      - "9050:9000"
    networks:
      - integration_sm_api_staging
    volumes:
      - './logs:/app/logs'
    restart: always



networks:
  integration_sm_api_staging:
    driver: bridge
