
services:
  integration_sm_api_feature_branch:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - TZ=America/Caracas
    container_name: feature_branch
    ports:
      - "9150:9000"
    networks:
      - feature_branch
    volumes:
      - './logs:/app/logs'

    restart: always



networks:
  feature_branch:
    driver: bridge
