
services:
  integration_sm_api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - TZ=America/Caracas
    ports:
      - "9150:9000"
    networks:
      - feature_branch
    restart: always



networks:
  feature_branch:
    driver: bridge
